Repository GDSC-SKHU/BodyLog-FrontEnd, pull requests merged in 2023-02, with the labels that each got.

#5 feat: 로그인 페이지 틀 작성
  bodylog/src/pages/Login.tsx
  bodylog/src/pages/_document.tsx
  bodylog/src/pages/index.tsx
  bodylog/src/styles/GlobalStyle.ts
Labels: documentation

#10 style: 회원가입 버튼 디자인 사소하게 변경
  bodylog/src/pages/Login.tsx
Labels: stlye

#7 feat: mypage 초기 작성 및 로그인 페이지 수정
  bodylog/src/pages/Login.tsx
  bodylog/src/pages/index.tsx
  bodylog/src/styles/GlobalStyle.ts
Labels: feat
