Repository GDSC-SKHU/BodyLog-FrontEnd, pull requests merged in 2023-03, with the labels that each got.

#14 feat: 디자인 변경 및 Prolog, Home 페이지 작성
  bodylog/public/Flogo.png
  bodylog/public/FoodLog.webp
  bodylog/public/back.png
  bodylog/public/calendar.png
  bodylog/public/eating habits.webp
  bodylog/public/foodlog.jpeg
  bodylog/public/home.png
  bodylog/public/logoimg.png
  bodylog/public/logotext.png
  bodylog/public/logout.png
  bodylog/public/next.png
  bodylog/public/smile.png
  bodylog/public/statistic.png
  bodylog/public/vegetables.webp
  bodylog/src/components/Nav.tsx
  bodylog/src/components/UnderNav.tsx
  bodylog/src/pages/Home.tsx
  bodylog/src/pages/Prolog1.tsx
  bodylog/src/pages/Prolog2.tsx
  bodylog/src/pages/Prolog3.tsx
  bodylog/src/pages/index.tsx
  bodylog/src/styles/GlobalStyle.ts
Labels: feat

#15 style: 캘린더 css 적용 작업 중
  bodylog/next.config.js
  bodylog/package-lock.json
  bodylog/package.json
  bodylog/src/api/hello.ts
  bodylog/src/components/Calendar.tsx
  bodylog/src/components/RenderCells.tsx
  bodylog/src/components/RenderDays.tsx
  bodylog/src/pages/Login.tsx
  bodylog/src/pages/index.tsx
  bodylog/src/pages/mypage.tsx
  bodylog/src/pages/register.tsx
  bodylog/src/styles/GlobalStyle.ts
Labels: stlye

#16 style: mypage.tsx 페이지 css 적용 중
  bodylog/next.config.js
  bodylog/src/components/Modal.tsx
  bodylog/src/components/Nav.tsx
  bodylog/src/components/RenderCells.tsx
  bodylog/src/components/UnderNav.tsx
  bodylog/src/pages/index.tsx
  bodylog/src/pages/mypage.tsx
  bodylog/src/pages/register.tsx
Labels: style

#17 feat: 모달창 기능 구현 완료
  .DS_Store
  bodylog/package-lock.json
  bodylog/package.json
  bodylog/public/CalendarPic/amount1.png
  bodylog/public/CalendarPic/amount2.png
  bodylog/public/CalendarPic/amount3.png
  bodylog/public/CalendarPic/default.png
  bodylog/public/CalendarPic/leftarrow.png
  bodylog/public/CalendarPic/rightarrow.png
  bodylog/public/CalendarPic/type1.png
  bodylog/public/CalendarPic/type2.png
  bodylog/public/CalendarPic/type3.png
  bodylog/src/components/Calendar/Calendar.tsx
  bodylog/src/components/Calendar/RenderCells.tsx
  bodylog/src/components/Calendar/RenderDays.tsx
  bodylog/src/components/Calendar/RenderHeader.tsx
  bodylog/src/components/Modal.tsx
  bodylog/src/components/Nav.tsx
  bodylog/src/pages/Login.tsx
  bodylog/src/pages/Mycalendar.tsx
Labels: feat

#18 Lgyn/11
  bodylog/public/Flogo-green.png
  bodylog/public/Flogo-white.png
  bodylog/src/components/Calendar/RenderCells.tsx
  bodylog/src/pages/Login.tsx
Labels: fix
